#!/bin/bash
set -e

./build-web $@

if [ "$1" == "--keygen" ]; then
    echo "building keygen"
    typedoc --name "Vecno WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/vecno-keygen ./build/docs/vecno-keygen.ts
elif [ "$1" == "--rpc" ]; then
    echo "building rpc"
    typedoc --name "Vecno WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/vecno-rpc ./build/docs/vecno-rpc.ts
elif [ "$1" == "--core" ]; then
    echo "building core"
    typedoc --name "Vecno WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/vecno-core ./build/docs/vecno-core.ts
elif [ "$1" == "--sdk" ]; then
    echo "building full"
    typedoc --name "Vecno WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/vecno ./build/docs/vecno.ts
else
    echo "building keygen"
    typedoc --name "Vecno WASM32 SDK - Key Generation" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/vecno-keygen ./build/docs/vecno-keygen.ts
    echo "building rpc"
    typedoc --name "Vecno WASM32 SDK - RPC" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/vecno-rpc ./build/docs/vecno-rpc.ts
    echo "building core"
    typedoc --name "Vecno WASM32 SDK - Core" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/vecno-core ./build/docs/vecno-core.ts
    echo "building full"
    typedoc --name "Vecno WASM32 SDK" --sourceLinkExternal --readme ./README.md --options ./build/docs/ --out ./docs/vecno ./build/docs/vecno.ts

fi