[package]
name = "vecno-wallet-cli-wasm"
description = "Vecno CLI wallet for WASM"
rust-version.workspace = true
version.workspace = true
edition.workspace = true
authors.workspace = true
include.workspace = true
license.workspace = true
repository.workspace = true

[features]
default = []

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
async-trait.workspace = true
js-sys.workspace = true
vecno-cli.workspace = true
wasm-bindgen-futures.workspace = true
wasm-bindgen.workspace = true
workflow-log.workspace = true
workflow-terminal.workspace = true
workflow-wasm.workspace = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-O", "--enable-bulk-memory", "--enable-nontrapping-float-to-int"]